site_name: CIB Mango Tree
site_author: CIB Mango Tree
site_description: "An interactive python terminal UI wrapper for Mango Tree analyzers."
site_url: https://cibmangotree.org
repo_url: https://github.com/civictechdc/mango-tango-cli
copyright: Copyright &copy; 2025 CIB Mango Tree
nav:
  - "Home":
      - "Overview": "index.md"
      - "License": "license.md"
  - "Guides":
      - "Getting Started":
          - "Overview": "guides/get-started/overview.md"
          - "Installation": "guides/get-started/installation.md"
      - "CLI design philosophy": "guides/architecture.md"
      - "Domains":
          - "Core Domain": "guides/domains/core-domain.md"
          - "Edge Domain": "guides/domains/edge-domain.md"
          - "Content Domain": "guides/domains/content-domain.md"
      - "Contributing to The Project": "guides/contributing.md"
  - "Reference (CLI)":
      - "Analyzer Interface": "reference/analyzer_interface.md"
      - "Components": "reference/components.md"
      - "App": "reference/app.md"
      - "Preprocessing": "reference/preprocessing.md"
      - "Terminal Tools": "reference/terminal_tools.md"
      - "Importing": "reference/importing.md"
      - "Meta": "reference/meta.md"
      - "Testing": "reference/testing.md"

theme:
  name: material
  logo: img/favicon.ico
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - content.code.copy
    - content.tooltips
    - toc.follow

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # search packages in the src folder
          options:
            show_root_heading: true
            # show_category_heading: true
            show_root_toc_entry: false
            show_root_full_path: true
            heading_level: 2
            docstring_style: google
            parameter_headings: true
            show_symbol_type_heading: True
            show_symbol_type_toc: True

markdown_extensions:
  - toc:
      baselevel: 2

  - pymdownx.snippets
